### ISSUE TITLE
Wired Connection not working after enabling AP.

### ISSUE THREAD

**Issue by Nam-Ereh-Won** [aangert/PiParty#168]
Decided to test out the wireless AP for management while headless. AP works just fine, but ethernet doesn't seem to be working afterward. Disabling AP does restore functionality.

**Comment by adangert** [comment]
Yeah I think that all internet connectivity stops after the AP is started. There may be a way to get around this somehow.

**Comment by Nam-Ereh-Won** [comment]
It was too late to look into why, but I found [this](https://github.com/adangert/JoustMania/blob/master/apfiles/interfaces#L12) this morning.

If I'm not mistaken, this line sets eth0 to not use an IP address at all.

I'm gonna test changing it to
`iface eth0 inet dhcp`

Looking through the rest of the config, everything else seems right and iptables appears to be set up to pass traffic from eth0 to wlan0 and vice versa.

**Comment by Nam-Ereh-Won** [comment]
Need to add `auto eth0` as well to get it working.

**Comment by adangert** [comment]
Thank you! If you want to make a pull request that would be helpful
